name: Production

on:
  push:
    tags:
      - 'latest/*'

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:

  frontend:

    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to prod
        run: |
          aws --region=us-east-1 eks update-kubeconfig --name libero-eks--franklin
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency build helm/prc
          helm upgrade -i prc--prod \
            --set images.frontend.tag=${IMAGE_TAG} \
            --set hostname=sciety.org \
            --set oldHostname=hive.review \
            --set googleTagManagerId=GTM-NX7CQB4 \
            --set disqusApiKey=${DISQUS_API_KEY} \
            --set twitterApiKey=${TWITTER_API_KEY} \
            --set twitterApiSecretKey=${TWITTER_API_SECRET_KEY} \
            --set twitterApiBearerToken=${TWITTER_API_BEARER_TOKEN} \
            --set postgresqlSecretName=hive-prod-rds-postgres \
            --wait \
            helm/prc
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISQUS_API_KEY: ${{ secrets.DISQUS_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_API_BEARER_TOKEN: ${{ secrets.TWITTER_API_BEARER_TOKEN }}

      - name: Notify Slack of success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: prc-general
          status: SUCCESS
          color: good

      - name: Notify Slack of failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: prc-general
          status: FAILED
          color: danger
